### ISSUE TITLE
How to get local price from Product?

### ISSUE THREAD

**Issue by snake302** [benjaminmayo/merchantkit#10]
Hi there.

So little tricky question - how to get local price from product with id at page load?

`   let product1 = Product.init(identifier: "my_id", kind: .subscription(automaticallyRenews: true))`

**Comment by benjaminmayo** [comment]
Use `Merchant.availablePurchasesTask` to load purchases, which contain the localized price details. If you are presenting a purchase UI, you should probably use `ProductInterfaceController` which does a lot of legwork for you. Please email if you have further questions.
