### ISSUE TITLE
Purchase with ProductInterfaceController

### ISSUE THREAD

**Issue by rebeloper** [benjaminmayo/merchantkit#12]
The commit method in the ProductInterfaceController needs a Purchase. How can I create one or how should I go about it?

Thanks

**Comment by benjaminmayo** [comment]
When using a `ProductInterfaceController`, you request the `ProductState` for a particular product from the controller. When a product is in the `purchasable` state, the `ProductState` enum has a `Purchase` as an associated value.

**Comment by rebeloper** [comment]
Awesome! Thanks for clearing this out.
