### ISSUE TITLE
ProductInterfaceController purchased state for an expired subscription

### ISSUE THREAD

**Issue by ekurutepe** [benjaminmayo/merchantkit#15]
I'm using an instance of `ProductInterfaceController` to drive a paywall. It refreshes the states for a few auto-renewing subscriptions to determine which ones should be shown to the user. 

When `productInterfaceController(_ controller:, didChangeStatesFor:)` gets called, it reports a `purchased` state for an expired subscription. 

While technically correct, this makes life hard for the API consumer requiring the conversion of the `ProductInfo` for the expired subscription into a `Purchase` to be able to populate the UI. 

I'd suggest reporting a `purchasable` state for an expired subscription. This is the more common use case I would imagine.

**Comment by benjaminmayo** [comment]
Expired subscriptions should not report as `purchased` indefinitely. However, MerchantKit has an inbuilt 'grace period' which prevents subscriptions from expiring immediately. It typically will not expire subscriptions until the receipt is refreshed on the next app launch. Is that maybe what you are seeing? 

If an expired subscription reports `purchased` forever, then that is a bug that will need fixing.

**Comment by ekurutepe** [comment]
Oh that makes total sense. My subscription is recently expired. I'm debugging something in the new user flow with short 5min sandbox subscriptions. So I'm definitely in the grace period. 

This means that I should be treating the `purchased` states as active subscriptions without checking the expiry date then, right?

**Comment by benjaminmayo** [comment]
Yeah, that's right. This is technically [documented here](https://github.com/benjaminmayo/merchantkit/blob/87cdd90bcbbfaa215ffdf3ee77a991d915d2bbbd/Source/Model/PurchasedProductInfo.swift#L4) but admittedly needs to be made much clearer in documentation and maybe more explicit in API.

**Comment by benjaminmayo** [comment]
I'm not 100% certain the current MerchantKit behaviour is compatible with what you are trying to do; the grace period stuff might conflict somewhere with non-mutually-exclusive subscription purchases. I've only tested/used it with standalone products. If you run into troubles, let me know and I'll consider if I need to add some kind of 'subscription group' API which can better describe this relationship.

**Comment by ekurutepe** [comment]
Thanks for your help. I see I've been overthinking this now. 

No need, I'm also using three subscriptions with different periods in this paywall. Strictly speaking what I'm doing is probably not necessary. I guess I'd be better off with hard-coding the product ids, assuming they're all purchasable, unless I get a purchased state after refresh.
