### ISSUE TITLE
Cocoapods update

### ISSUE THREAD

**Issue by ahmetkgunay** [benjaminmayo/merchantkit#17]
Your cocopods version of this library looks it has 0.6.0 version but updated version should be 0.9?

**Comment by benjaminmayo** [comment]
Can you verify if you are seeing this still? it should be in sync.

**Comment by ahmetkgunay** [comment]
Unable to find a pod with name, author, summary, or description matching `MerchantKit` :(

**Comment by benjaminmayo** [comment]
Can you try clearing the Cocoapods cache? Run this, and then try searching again:

````
pod setup
rm -rf ~/Library/Caches/Cocoapods
````

The pod is [live on the Cocoapods website](https://cocoapods.org/pods/MerchantKit), so I think everything is setup correctly on my end.
