### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by lennartkerkvliet** [benjaminmayo/merchantkit#18]
It would be nice to use MerchantKit with the Carthage dependency manager, which requires a shared framework scheme.

**Comment by benjaminmayo** [comment]
I have no philosophical opposition to Carthage but I just have never used it myself. Happy to accept pull requests that make the project Carthage compatible.

**Comment by benjaminmayo** [comment]
Closing as https://github.com/benjaminmayo/merchantkit/pull/19 was merged into master. I'll tag a new release soon.
