### ISSUE TITLE
Objective-c

### ISSUE THREAD

**Issue by bcbeta** [benjaminmayo/merchantkit#2]
It would be much appreciated if this framework were compatible with objective-c projects.  There aren't any obj-c frameworks that have been updated in the past couple of years.  Thanks!

**Comment by benjaminmayo** [comment]
Yeah, the lack of up-to-date IAP convenience frameworks is what ultimately resulted in me making this for my own projects. I doubt Objective-C compatibility is on the cards; MerchantKit relies heavily on enums and other Swift-exclusive paradigms.
