### ISSUE TITLE
iOS 12

### ISSUE THREAD

**Issue by CocoaPriest** [benjaminmayo/merchantkit#21]
Hey, is there a reason for iOS 12 as min. version?

**Comment by benjaminmayo** [comment]
I had to bump to 11.3 for some subscription related stuff, so I figured I might as well bump to 12.0 and break the pain early. Until `MerchantKit` hits a 1.0 release, I am willing to move rapidly. I am currently planning to hit 1.0 alongside Swift 5, so sometime in the next couple of months. This work is already underway in the branch. The major version number will then signify a promise of general API stability and prolonged OS compatibility.

If you want to use the framework with earlier OS versions, feel free at your own leisure.

**Comment by CocoaPriest** [comment]
Thanks for the clarification.

**Comment by benjaminmayo** [comment]
Due to some unexpected circumstances, I have actually restored iOS 11 compatibility on master and this will be part of a 0.11 release coming soon.
