### ISSUE TITLE
Possible issue with signin/signout of apple store

### ISSUE THREAD

**Issue by timprepscius** [benjaminmayo/merchantkit#27]
Truthfully, I do not know what is correct behavior.

I sign into iTunes & App Store
I purchase a renewing subscription product (sandbox)
I sign out of iTunes

App still considers subscription valid.

Is it valid?  I don't know.  If it shouldn't be, the receipts probably need to be tied to some anonymified-user-id?  Not a big deal in any case.

Anyhow, your lib seems (over the last couple days) to be working nicely.  Thanks for this work.

**Comment by benjaminmayo** [comment]
MerchantKit is lenient to the user. The policy is essentially the framework will happily consider a subscription active until the next known renewal period elapses — anytime there is ambiguity about the receipt status. Signing out is one such instance of ambiguity.

**Comment by timprepscius** [comment]
Ok.  Yeah, I'm not sure if this is an issue or not.  Or what changes would be necessary to make a "strict" option.  For me, it is completely fine how you have it.

**Comment by benjaminmayo** [comment]
Yeah, down the line, it may be worth having configuration options for this. As it stands, it covers 90% of the use-cases of developers who are looking for straightforward, server-less, subscription management. 

(And thanks for the kind words.)
