### ISSUE TITLE
Regular price vs current price

### ISSUE THREAD

**Issue by Prince2k3** [benjaminmayo/merchantkit#29]
Is there a way to pull the regular price versus the promotional price applied to the product/subscription

Thanks

**Comment by benjaminmayo** [comment]
`Purchase.price` is the normal price. Inspect the `Purchase.subscriptionTerms.introductoryOffer` to see introductory pricing.

**Comment by Prince2k3** [comment]
I'm guessing Promotional Offers is new because IntroductoryOffer has its own tab on App Store Connect, which works. The company has setup an introductory offer of free trail for a duration and then added a promotional offer for the first year. I was hoping to pull these prices from MerchantKit. But it's looking like I'll just hard code everything for now. (Like how in Example it using ProductDatabase)

**Comment by benjaminmayo** [comment]
Ah, you mean the new Promotional Offers introduced in iOS 12.2. Yeah, these aren't exposed through `MerchantKit` yet — this is on the list to be supported in a future framework version.

**Comment by Prince2k3** [comment]
Alright. Closing!
