### ISSUE TITLE
how verification of auto renewable subscriptions work here?

### ISSUE THREAD

**Issue by bizibizi** [benjaminmayo/merchantkit#3]

**Comment by benjaminmayo** [comment]
There are multiple options. The included `ServerReceiptValidator` sends a network request to the iTunes Store server; this requires bundling the shared secret inside the project. The preferred method is to use the `LocalReceiptValidator` which will check the App Store receipt, all locally, for the expiry date and other metadata. 

Both these methods are not wholly fool-proof but the goal of the project is not to eliminate all possible piracy. 

You can make your own validator (and use it in the delegate) if you want to customise this validation process yourself.
