### ISSUE TITLE
Delegate methods

### ISSUE THREAD

**Issue by randomiser** [benjaminmayo/merchantkit#4]
Xcode 9.3 & Cocoapods 1.5.0

After installing and creating a simple class to test the delegate methods I repeatadly get the following issue:

<img width="1241" alt="error" src="https://user-images.githubusercontent.com/2062188/38587239-da816746-3d74-11e8-955a-3ca4f189fb4f.png">

Do you have any ideas as to why this my be happening?

**Comment by benjaminmayo** [comment]
Do you have the `Result` type declared elsewhere in the containing project? The names might be conflicting. You can try specifying `MerchantKit.Result` in the signature.

**Comment by randomiser** [comment]
Thanks for the fast response! Yeah it was that. Hadn't noticed it was included elsewhere. Thanks heaps.

**Comment by benjaminmayo** [comment]
I have run into this issue myself. I have pondered renaming the type to something more specific like `TaskResult`.

**Comment by randomiser** [comment]
Is it only used in the context of a "task"? Another option could be to call it something like ProcessingResult perhaps.

**Comment by benjaminmayo** [comment]
It's solely used by the tasks in the public API; internal to the framework it threads through several different things. I think I'll bring up the naming collisions up on the Swift forums, and at least push for a better error message to describe the root cause of the build-time issue.

**Comment by benjaminmayo** [comment]
I have reported this as a [Swift bug here](https://bugs.swift.org/browse/SR-7505), referencing this issue as a real-world example of how the produced error messages are inscrutable and confusing.

**Comment by randomiser** [comment]
Thanks for reporting the issue. Definitely worth while.
