### ISSUE TITLE
Billing Grace Period support

### ISSUE THREAD

**Issue by ankrv** [benjaminmayo/merchantkit#40]
There is this new turn on Billing Grace Period button for subscriptions in the App Store Connect with the following explanation:

> A billing grace period lets subscribers retain access to your app's paid content even after their subscription expires due to a billing issue. If Apple successfully recovers the subscription during this grace period, you will not experience any interruption in your revenue.

Does MerchantKit support Billing Grace Period?

P.S. Thank you for the best subscription solution!

**Comment by benjaminmayo** [comment]
This is news to me! Is there any more documentation on this I wonder.

**Comment by ankrv** [comment]
Yep, it’s from WWDC2019 and started this fall.

Implementation from the session pdf:

1. Opt-in via App Store Connect
2. New field in /verifyReceipt - grace_period_expires_date
3. Keep service active during grace period

https://developer.apple.com/videos/play/wwdc2019/302/

**Comment by benjaminmayo** [comment]
As far as I can tell, these fields are not available in local receipts. MerchantKit should ideally support all types of validation but local validation is by far the most popular usage. And looking like it just won't be possible, I have been thinking about adding a 'leeway' duration parameter to the configuration though. This should help the user experience when receipts aren't refreshed exactly on time, but I don't think that would qualify as complying to the grace periods.

**Comment by ankrv** [comment]
Sound good to me, I think the offline leeway duration is all that is needed. They use 6 days for weekly subscriptions, 16 days for everything else:

https://developer.apple.com/documentation/storekit/in-app_purchase/reducing_involuntary_subscriber_churn

**Comment by benjaminmayo** [comment]
Leeway duration is now included in the latest release of MerchantKit. It defaults to 30 days (I have noticed issues where the local receipts are not updated appropriately, so I believe the 30 day buffer will give StoreKit time to properly refresh receipts). I believe this implementation will also now correctly support the Billing Grace Period feature, even though the documentation strictly only refers to server-side validation.
