### ISSUE TITLE
Gets "Cannot Connect to iTunes Store" after upgrading plan

### ISSUE THREAD

**Issue by denandreychuk** [benjaminmayo/merchantkit#44]
Hi! I faced with a problem related to subscription upgrading. Not sure exactly if it's related to MerchantKit, but I  I get  "Cannot Connect to iTunes Store" every time I upgrade plan for auto-renewable subscription.

If I have already purchased, for example, "weekly" subscription and then tries to upgrade my plan to "monthly", I got "Cannot Connect to iTunes Store" **after** successfully complete transaction. The last part is weird. I got popup from Apple that everythings good, and that I was billed, and after that I receive error in didCommit delegate method of ProductInterfaceController.

Please, let me know you have any idea what could be the problem.

Best regard, Den

**Comment by benjaminmayo** [comment]
Is this testing on a real device?

**Comment by denandreychuk** [comment]
ye, on real device.

**Comment by benjaminmayo** [comment]
Hmm, I can't explain that then. I'd be surprised if it was a MerchantKit issue — but can't immediately rule it out.

**Comment by denandreychuk** [comment]
Any updates on this?

Also, I have one more question. Does MerchantKit support promoted products?

**Comment by denandreychuk** [comment]
Also, I have one more question. Does MerchantKit support promoted products: https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue ?

**Comment by benjaminmayo** [comment]
No idea on your initial problem. And yes it does support promoted products. By default, the purchase flow starts immediately when receiving a promoted product event. You can optionally override this behaviour using the delegate method `func merchant(_ merchant: Merchant, didReceiveStoreIntentToCommit purchase: Purchase) -> StoreIntentResponse`

**Comment by benjaminmayo** [comment]
Closing this as I cannot make progress on your initial issue with the description provided. If you can do more testing and nail down a MerchantKit problem, please open a new issue with details.
