### ISSUE TITLE
Receipt & Grace Period. 

### ISSUE THREAD

**Issue by rizwanhaider91** [benjaminmayo/merchantkit#45]
There is no documentation for receipt and when we use subscription with free trial then no information when it will expire and when complete subscription will expire. I am unable to find proper documentation. There is no prior information when free trial will finish and when make payment for selected subscription.

**Comment by benjaminmayo** [comment]
I'm sorry but the available documentation is what I have the bandwidth for. The example project should be understandable, the README should get you off the ground, and the public API of the framework is thoroughly commented. I am obviously open to other people submitting richer documentation resources, via pull requests.
