### ISSUE TITLE
How does one get a list of available purchases?

### ISSUE THREAD

**Issue by jln19** [benjaminmayo/merchantkit#47]
`registeredProducts` is private. 

`product(withIdentifier productIdentifier: String)` seems to be the only public method for retrieving a product, but that requires calling it for each individual identifier. Is it by design to not have a way to retrieve all products?

**Comment by benjaminmayo** [comment]
The client has to feed `Merchant` with products to register, so the knowledge of registered products exists outside of `Merchant` already. 

The best way to do this is [shown in the Example project](https://github.com/benjaminmayo/merchantkit/blob/master/Example/Source/ProductDatabase.swift). You create the `Product` instance and then refer to that throughout the app, which retains a semantic meaning about what the product actually represents. Note that the example `ProductDatabase` also exposes an `allProducts` array as a convenience accessor to pass straight to `merchant.register(...)`
