### ISSUE TITLE
How to trigger FetchingState.FailureReason ?

### ISSUE THREAD

**Issue by peterwarbo** [benjaminmayo/merchantkit#48]
I'm trying to test my app in airplane mode but even though it's on `productInterfaceController.fetchingState` doesn't return a failed state?

**Comment by benjaminmayo** [comment]
I have noticed that the StoreKit framework appears to implement some caching procedures lately. You should try deleting the application and reinstalling it, with Airplane Mode enabled.

**Comment by peterwarbo** [comment]
Thanks that worked 👍
