### ISSUE TITLE
Crash when force unwrapping `transaction.error!`

### ISSUE THREAD

**Issue by pkamb** [benjaminmayo/merchantkit#49]
I'm attempting to purchase a sandbox environment IAP with my non-sandbox Apple ID.

Using tag `0.14.0`.

This displays an alert error message:

 > You are not authorized to make purchases of this InApp in Sandbox at this time.
 > [Environment: Sandbox]

and then hits the delegate method in `StoreKitTransactionObserver.swift`:

    fileprivate func failPurchase(for transaction: SKPaymentTransaction, on paymentQueue: SKPaymentQueue) {
        self.delegate?.storeInterface(self.storeInterface, didFailToPurchaseProductWith: transaction.payment.productIdentifier, error: transaction.error!)
        
        paymentQueue.finishTransaction(transaction)
    }

The `transaction.error!` force unwrap there is crashing as `error` is nil.

    po transaction
    <SKPaymentTransaction: 0x600000016030>

    po transaction.error
    nil

I'm going to switch to using a Sandbox account, which should hopefully fix the issue. But wanted to open an Issue here before I forget.

**Comment by benjaminmayo** [comment]
Thanks for flagging this. We had a [similar issue before](https://github.com/benjaminmayo/merchantkit/pull/23). `StoreKit`'s documented nullability conditions are not adhered to religiously by the framework, particularly when mixing sandbox/test/production accounts and receipts.

**Comment by benjaminmayo** [comment]
Added a [fallback error here](https://github.com/benjaminmayo/merchantkit/commit/8c30d48b71a2610762b494125d5043f60853da7a).
