### ISSUE TITLE
Seems like MerchantDelegate Regression

### ISSUE THREAD

**Issue by denandreychuk** [benjaminmayo/merchantkit#51]
After updated to 0.14.0, MerchantDelegate don't calls `didChangeStatesFor` method in Sandbox when subscription expired. For example, I bought weekly subscription = 3 min period in Sandbox, but delegate method don't calls.

**Comment by benjaminmayo** [comment]
The validators now have an [inbuilt leeway](https://github.com/benjaminmayo/merchantkit/blob/f3133898fed300e61d1a6d175bc850b2ef9a1796/Source/Receipt%20Validators/ReceiptValidator.swift#L8). The reason for this is that the iTunes Store server does not send renewal receipts in a timely fashion. It can sometimes take many days past the renewal date for the device to receive a fresh receipt. The current framework default is 30 days. You can customize the configuration if you need to use a different leeway period.
