### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by sderuiter** [benjaminmayo/merchantkit#52]
Will this framework ever be released for the Swift Package Manager?

**Comment by benjaminmayo** [comment]
I'm waiting on localized resource support for packages to be released. Then, I plan on making it support SwiftPM as the primary method.

**Comment by sderuiter** [comment]
Thank you. Is there any indication if and when this will be released for SwiftPM?

**Comment by benjaminmayo** [comment]
The Swift Evolution proposal was approved in the last few weeks so it should be part of Swift 5.3.
