### ISSUE TITLE
How to disable introductory offers for ineligible users ?

### ISSUE THREAD

**Issue by j0ris** [benjaminmayo/merchantkit#54]
I am not able to find if MerchantKit can disable introductory offers for customers who have previously received an introductory offer for the given subscription...

Does MerchantKit handle this ?

**Comment by benjaminmayo** [comment]
If StoreKit does not nil out the property on its own, then the answer is no. It would be a nice thing to add - I can’t remember the details offhand but it’s a little tricky.
