### ISSUE TITLE
Could you please update Cocoapods library?

### ISSUE THREAD

**Issue by denandreychuk** [benjaminmayo/merchantkit#55]
I want to include your framework with the last changes (a few commits that not included in 0.14.0) as a dependency of my internal framework. The problem is, that `:git` tag in `.podspecs` (not Podfile!) is not supported.

I receive these error: Podspecs cannot specify the source of dependencies. The `:git` option is not supported. `:git` can be used in the Podfile instead to override global dependencies.

0.14.1 or 0.15.0 is expected.

**Comment by benjaminmayo** [comment]
The changes after 0.14.0 aren’t properly finished yet. Cocoapods is up to date.
