### ISSUE TITLE
PurchaseRecord does not conform to protocol 'Equatable'

### ISSUE THREAD

**Issue by snake302** [benjaminmayo/merchantkit#6]
Xcode 9.2, Cocoapods 1.4.0, MerchantKit 0.5.0

I can't compile framework

<img width="807" alt="screen shot 2018-04-21 at 13 46 38" src="https://user-images.githubusercontent.com/1431423/39083244-77e365b4-456a-11e8-9c5a-699b06fc9a73.png">

**Comment by snake302** [comment]
The same situation with other files
<img width="852" alt="screen shot 2018-04-21 at 13 56 09" src="https://user-images.githubusercontent.com/1431423/39083367-db881636-456b-11e8-8e63-d28dc6bf1d05.png">
<img width="822" alt="screen shot 2018-04-21 at 13 56 26" src="https://user-images.githubusercontent.com/1431423/39083368-dba7b0ea-456b-11e8-97e6-b5f65d7dc374.png">

**Comment by benjaminmayo** [comment]
You need to be compiling with Swift 4.1, which isn't part of Xcode 9.2 IIRC ... can you verify this is the cause of your problem? The project uses the new auto-synthesised `Equatable` and `Hashable` conformances. The MerchantKit.podspec declares that Swift 4.1 is required so I'm not sure why Cocoapods let you install it.

**Comment by snake302** [comment]
So yep, update solved the problem, thanks!
 
Upgraded macOS 10.12.6 => 10.13.4
Updated Xcode 9.2 => 9.3
Swift 4.0 => Swift 4.1
