### ISSUE TITLE
Auto-renewable subscription issue

### ISSUE THREAD

**Issue by endogenesis** [benjaminmayo/merchantkit#60]
Environment: sandbox
It seems that after purchasing an auto-renewable subscription, it will forever remain in .purchased status, regardless of expire date.

Example on screenshot:
<img width="1131" alt="Screen Shot 2020-08-31 at 23 45 34" src="https://user-images.githubusercontent.com/4007952/91767510-eb3dfb00-ebe4-11ea-8bea-77f9a7e644cd.png">

**Comment by benjaminmayo** [comment]
This is working as intended. The expiryDate in the info is based on the data from the last fetched receipt. There is a 30-day buffer which gives time for the iTunes Store to send new receipts. It can be slow to refresh sometimes and MerchantKit's default policy is forgiving. You can customize this period of time by changing the configuration, but I don't recommend it.

**Comment by iblagajic** [comment]
I was wondering the same, thanks for the explanation!
@benjaminmayo do you perhaps have some instructions/recommendations for expiry testing (in sandbox)?
