### ISSUE TITLE
[Suggestion] Add applicationUsername to Purchase for fraud detection

### ISSUE THREAD

**Issue by xuaninbox** [benjaminmayo/merchantkit#7]
based on doc applicationusername and help apple to detect irregular activity, it would be great to add it for Purchase & Restore.

https://developer.apple.com/documentation/storekit/skpayment/1506116-applicationusername

restore: https://developer.apple.com/documentation/storekit/skpaymentqueue/1505992-restorecompletedtransactions

**Comment by benjaminmayo** [comment]
This is a reasonable request. The question is, should this be a setting on the `Merchant` or a more fine-grained option on an individual invocation of a ‘commit purchase’ task? I’m leaning towards the former - this defies the StoreKit pattern but I can’t see a need to customise this on a per-transaction basis.

**Comment by xuaninbox** [comment]
I see.. it does differ from the pattern, but i do think given per-transaction applicationUsername might be better.

maybe an optional delegate to ask for applicationUsername before sending it to SKPaymentQueue?

**Comment by benjaminmayo** [comment]
I think a delegate for this is too heavyweight; most apps will never need this. I’m inclined to roll with a simple config property on the `Merchant` for now - I can add customisation points down the road if it is really in demand.

**Comment by benjaminmayo** [comment]
Support for setting the `applicationUsername` is now included, with this commit: https://github.com/benjaminmayo/merchantkit/commit/07dbb6f1d6c7d0c292009083b3be646a2868c895

Usage: `merchant.storeParameters.applicationUsername = "accountUsername"`.
