### ISSUE TITLE
Xcode StoreKit Configuration with Simulator: Refund and deleting transactions is not supported

### ISSUE THREAD

**Issue by MikeChongCan** [benjaminmayo/merchantkit#70]
1. Add a StoreKit configuration file to the Example project. like:
    <img width="1375" alt="image" src="https://user-images.githubusercontent.com/2396817/118418405-e37aa400-b6ea-11eb-9778-69c889e4af9d.png">
2. Test the store kit purchase and refund (or delete)

(You can `git clone https://github.com/imWildCat/merchantkit-forked-example` to test. Basically, this fork does not change anything except adding the StoreKit configuration file)

## Actual behavior

After refund or deleting, the state is still `purchased`

<img width="1236" alt="s" src="https://user-images.githubusercontent.com/2396817/118418552-68fe5400-b6eb-11eb-8060-2537908f27f1.png">

https://user-images.githubusercontent.com/2396817/118418539-5e43bf00-b6eb-11eb-8414-fb085261dc9e.mov

## Expected behavior

After refund or deleting, the state is still `purchasable`, compared with Apple's sample code: <https://developer.apple.com/documentation/swiftui/fruta_building_a_feature-rich_app_with_swiftui>

https://user-images.githubusercontent.com/2396817/118418541-61d74600-b6eb-11eb-94d5-79085dc4d3db.mov

**Comment by benjaminmayo** [comment]
This should be fixed on master.
