### ISSUE TITLE
in App purchases from server

### ISSUE THREAD

**Issue by pixelbendr** [benjaminmayo/merchantkit#8]
Hello,

Can your library be used for dynamic in app purchases?

 for example a user on our platform is allowed to create a product catalogue and enable in app purchasing for paid items. 

Regards.
Evans.

**Comment by benjaminmayo** [comment]
The issues inbox is not a support line. Closing as off-topic.

**Comment by pixelbendr** [comment]
Okay, thank you . I have emailed the issue to you as support. 

Regards.
